
export const projectData = {
    id: "1234567",
    title: "2Live",
    type: "Music Video",
    location: "LA",
    shooting_format: "Digital",
    delivery_format: "Digital",
    client: {
        name: "Hitboy",
        logo: "link to file TODO",
    },
    sections: [
        {
            title: "Pre-Production | Wrap Labor",
            type: "A",
            lineItems: [
                {
                    title: "Supervising Producer",
                    cost: 2000,
                    rate: 1000,
                    days: 2,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Line Producer",
                    cost: 3200,
                    rate: 800,
                    days: 4,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Director of Photography",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AC",
                    cost: 300,
                    rate: 300,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AD",
                    cost: 200,
                    rate: 200,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Production Assistant - Set",
                    cost: 100,
                    rate: 100,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                // {
                //     title: "Supervising",
                //     cost: 2000,
                //     rate: 1000,
                //     days: "2",
                //     has_overtime: false,
                //     overtime_rate: null,
                // }
            ],
            subtotal: 6300,
            total: 6300
        },
        {
            title: "Shooting Labor",
            type: "B",
            lineItems: [
                {
                    title: "Supervising Producer",
                    cost: 1000,
                    rate: 1000,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Line Producer",
                    cost: 800,
                    rate: 800,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Director of Photography",
                    cost: 1500,
                    rate: 1500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AC",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "2nd AC",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Production Manager",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Gaffer",
                    cost: 700,
                    rate: 700,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Best Electric",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Swing",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Key Grip",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Best Grip",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Construction Build",
                    cost: 1000,
                    rate: 1000,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Wardrobe + Styling",
                    cost: 2200,
                    rate: 2200,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AD",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Production Assistant - Set",
                    cost: 1000,
                    rate: 250,
                    days: 1,
                    number_of_staff: 4,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 12500,
            total: 12500
        }
    ]
}