
export const projectData = {
    id: "1234567",
    title: "2Live",
    type: "Music Video",
    location: "LA",
    shooting_format: "Digital",
    delivery_format: "Digital",
    client: {
        name: "Hitboy",
        logo: "link to file TODO",
    },
    sections: [
        {
            title: "Pre-Production | Wrap Labor",
            type: "A",
            line_items: [
                {
                    title: "Supervising Producer",
                    cost: 2000,
                    rate: 1000,
                    days: 2,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Line Producer",
                    cost: 3200,
                    rate: 800,
                    days: 4,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Director of Photography",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AC",
                    cost: 300,
                    rate: 300,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AD",
                    cost: 200,
                    rate: 200,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Production Assistant - Set",
                    cost: 100,
                    rate: 100,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                // {
                //     title: "Supervising",
                //     cost: 2000,
                //     rate: 1000,
                //     days: "2",
                //     has_overtime: false,
                //     overtime_rate: null,
                // }
            ],
            subtotal: 6300,
            total: 6300
        },
        {
            title: "Shooting Labor",
            type: "B",
            line_items: [
                {
                    title: "Supervising Producer",
                    cost: 1000,
                    rate: 1000,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Line Producer",
                    cost: 800,
                    rate: 800,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Director of Photography",
                    cost: 1500,
                    rate: 1500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AC",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "2nd AC",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Production Manager",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Gaffer",
                    cost: 700,
                    rate: 700,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Best Electric",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Swing",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Key Grip",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Best Grip",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Construction Build",
                    cost: 1000,
                    rate: 1000,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Wardrobe + Styling",
                    cost: 2200,
                    rate: 2200,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "1st AD",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Production Assistant - Set",
                    cost: 1000,
                    rate: 250,
                    days: 1,
                    num: 4,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 12500,
            total: 12500
        },
        {
            title: "Pre-Production | Wrap Expenses",
            type: "C",
            line_items: [
                {
                    title: "Auto Rentals",
                    cost: 1500,
                    rate: 1500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Trucking",
                    cost: 400,
                    rate: 400,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Casting Director",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 2400,
            total: 2400
        },
        {
            title: "Location & Travel",
            type: "D",
            line_items: [
                {
                    title: "Location Fees",
                    cost: 1500,
                    rate: 1500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Permits",
                    cost: 900,
                    rate: 900,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Boat Rentals",
                    cost: 15000,
                    rate: 15000,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Dressing Room Vehicles",
                    cost: 650,
                    rate: 650,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Breakfast",
                    cost: 400,
                    rate: 400,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Lunch",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Craft Services",
                    cost: 300,
                    rate: 300,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 19350,
            total: 19350
        },
        {
            title: "Makeup, Wardrobe, And Animals",
            type: "E",
            line_items: [
                {
                    title: "Wardrobe Rentals",
                    cost: 2800,
                    rate: 2800,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 2800,
            total: 2800
        },
        {
            title: "STUDIO | STAGE RENTAL / EXPENSES",
            type: "F",
            line_items: [],
            subtotal: 0,
            total: 0,
        },
        {
            title: "Art Department Labor",
            type: "G",
            line_items: [
                {
                    title: "Production Designer",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Art Assts",
                    cost: 200,
                    rate: 200,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 700,
            total: 700,
        },
        {
            title: "Art Department Expenses",
            type: "H",
            line_items: [
                {
                    title: "Prop Rental",
                    cost: 500,
                    rate: 500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 500,
            total: 500,
        },
        {
            title: "EQUIPMENT COSTS",
            type: "I",
            line_items: [
                {
                    title: "Camera Rental",
                    cost: 1600,
                    rate: 1600,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Lighting Rental",
                    cost: 2500,
                    rate: 2500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Grip Rental",
                    cost: 1000,
                    rate: 1000,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Walkie Talkie Rental",
                    cost: 120,
                    rate: 120,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Steadicam",
                    cost: 1400,
                    rate: 1400,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Stills Lighting",
                    cost: 600,
                    rate: 600,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 7220,
            total: 7220,
        },
        {
            title: "FILMSTOCK, DEVELOP AND PRINT",
            type: "J",
            line_items: [],
            subtotal: 0,
            total: 0,
        },
        {
            title: "MISCELLANEOUS",
            type: "K",
            line_items: [
                {
                    title: "Payroll Services",
                    cost: 2000,
                    rate: 2000,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 2000,
            total: 2000,
        },
        {
            title: "DIRECTOR | CREATIVE FEES",
            type: "L",
            line_items: [
                {
                    title: "Director Prep",
                    cost: 4500,
                    rate: 1500,
                    days: 3,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Director Shoot",
                    cost: 4000,
                    rate: 4000,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Co Director",
                    cost: 3000,
                    rate: 3000,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 11500,
            total: 11500,
        },
        {
            title: "TALENT LABOR",
            type: "M",
            line_items: [
                {
                    title: "O/C Principals",
                    cost: 7500,
                    rate: 500,
                    days: 1,
                    num: 15,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 7500,
            total: 7500,
        },
        {
            title: "TALENT EXPENSES",
            type: "N",
            line_items: [],
            subtotal: 0,
            total: 0,
        },
        {
            title: "POST PRODUCTION LABOR",
            type: "O",
            line_items: [
                {
                    title: "Post Producer",
                    cost: 1000,
                    rate: 1000,
                    days: null,
                    num: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Offline Editor",
                    cost: 3000,
                    rate: 3000,
                    days: null,
                    num: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Assistant Editor",
                    cost: 500,
                    rate: 500,
                    days: null,
                    num: 1,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 4500,
            total: 4500,
        },
        {
            title: "EDITORIAL | FINISHING | POST PRODUCTION",
            type: "P",
            line_items: [
                {
                    title: "Color Correction",
                    cost: 1500,
                    rate: 1500,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Visual Effects",
                    cost: 3000,
                    rate: 3000,
                    days: 1,
                    num: null,
                    has_overtime: false,
                    overtime_rate: null,
                },
                {
                    title: "Hard Drive",
                    cost: 800,
                    rate: 400,
                    days: 1,
                    num: 2,
                    has_overtime: false,
                    overtime_rate: null,
                },
            ],
            subtotal: 5300,
            total: 5300,
        },
    ],
    notes: null,
}